apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parflow-subset-v1-
  namespace: argo
spec:
  entrypoint: parflow-subset-v1

  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters:
    - name: pfinput
      value: /srv/input
    - name: shape
      value: /srv/output/watershed.shp
    - name: output
      value: /srv/output
    - name: label
      value: pf-subset-job

  templates:
  - name: parflow-subset-v1
    inputs:
      parameters:
        - name: pfinput
        - name: shape
        - name: output
        - name: label
      artifacts:
        - name: pfinput-data
          path: /srv/input
          gcs:
            bucket: subsetter-static-input
            key: pfconus.v1.0
            serviceAccountKeySecret:
              name: my-gcs-creds
              key: serviceAccountKey
        - name: pfoutput-data
          path: /srv/output
          gcs:
            bucket: subsetter-outputs
            key: q1w2e3r4t5y6u7i8o9p0
            serviceAccountKeySecret:
              name: my-gcs-creds
              key: serviceAccountKey
    container:
      image: cuahsi/parflow-subset-argo:v1
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
          ephemeral-storage: "1Gi"
        limits:
          memory: "2Gi"
          cpu: 2
          ephemeral-storage: "2Gi"
      command: ["python", "-u", "entry.py"]
      args: ["{{inputs.parameters.label}}",
             "{{inputs.parameters.shape}}",
             "{{inputs.parameters.pfinput}}",
             "{{inputs.parameters.output}}"]
    outputs:
      artifacts:
        - name: subset-results
          path: /srv/output
          gcs:
            bucket: subsetter-outputs
            key: subset-output.gz
            serviceAccountKeySecret:
              name: my-gcs-creds
              key: serviceAccountKey
